# Generated by Django 5.1.6 on 2025-04-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_projecttag_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ProjectTag',
        ),
    ]
