# Generated by Django 5.1.6 on 2025-04-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_project_id_datafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
