# Generated by Django 5.1.6 on 2025-04-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_project_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='type',
            field=models.CharField(choices=[('CSV', 'CSV File')], default='CSV', max_length=4),
            preserve_default=False,
        ),
    ]
