# Generated by Django 5.1.6 on 2025-04-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_datafile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='type',
        ),
        migrations.AddField(
            model_name='datafile',
            name='filetype',
            field=models.CharField(choices=[('CSV', '.csv')], default='CSV', max_length=4),
            preserve_default=False,
        ),
    ]
