# Generated by Django 5.1.6 on 2025-04-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_projectpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
