# Generated by Django 5.1.6 on 2025-04-24 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_datafile_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
