# Generated by Django 5.1.6 on 2025-05-01 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_projectpin_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaderParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('data_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.datafile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
        ),
    ]
