# Generated by Django 5.1.6 on 2025-05-01 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_loaderparams'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('func_name', models.CharField(max_length=100)),
                ('info', models.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
        ),
        migrations.DeleteModel(
            name='LoaderParams',
        ),
    ]
