# Generated by Django 5.1.6 on 2025-05-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_functionparams_delete_loaderparams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FunctionParams',
        ),
    ]
