# Generated by Django 5.1.6 on 2025-05-03 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_functionparams'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutimeRenderResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.TextField(blank=True)),
                ('func_params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.functionparams')),
            ],
        ),
    ]
