# Generated by Django 5.1.6 on 2025-05-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_rutimerenderresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RutimeRenderResult',
            new_name='RuntimeRenderResult',
        ),
    ]
