# Generated by Django 5.1.6 on 2025-05-05 08:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_rename_rutimerenderresult_runtimerenderresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('info', models.JSONField(blank=True)),
                ('status', models.CharField(choices=[('NE', 'Not Executed'), ('EX', 'Executing'), ('OK', 'Done'), ('ER', 'Errored!')], default='NE')),
                ('func', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.functionparams')),
            ],
        ),
    ]
