# Generated by Django 5.1.6 on 2025-05-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_functionstatus_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='display_in_guest_mode',
            field=models.BooleanField(default=False),
        ),
    ]
