# Generated by Django 5.1.6 on 2025-05-30 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_datafile_display_in_guest_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimePermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
        ),
    ]
